var gallery = [
  {city: "Budapest",
  country: "Hungary",
  link: "gallery/budapest.jpg",
  info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque congue vehicula dapibus. Aenean venenatis fringilla libero, sed dignissim felis iaculis imperdiet. In iaculis purus erat, a sodales lectus maximus ut."},
  {city: "Buenos Aires",
  country: "Argentina",
  link: "gallery/buenos_aires.jpg",
  info: "Cras tristique lectus est, eu euismod metus laoreet id. Aenean a tortor in nulla pellentesque condimentum."},
  {city: "Melbourne",
  country: "Australia",
  link: "gallery/melbourne.jpg",
  info: "Suspendisse a nulla vel enim bibendum euismod in ac nulla. Cras sit amet egestas mauris. Nulla aliquam pharetra dolor, at interdum nisi sagittis at. Sed pharetra, ligula et faucibus aliquet, nulla arcu condimentum nunc, sit amet blandit mauris massa nec diam."},
  {city: "Moscow",
  country: "Russia",
  link: "gallery/moscow.jpg",
  info: "Sed non dui ac odio bibendum bibendum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."},
  {city: "San Francisco",
  country: "USA",
  link: "gallery/san_francisco.jpg",
  info: "Proin faucibus risus dolor, at lobortis ante hendrerit ut. Aliquam ut velit sit amet erat dapibus auctor. Nam bibendum congue congue."},
  {city: "Havana",
  country: "Cuba",
  link: "gallery/havana.jpg",
  info: "Proin at rutrum quam. Duis lacinia augue nibh, quis facilisis ligula porttitor sed. Etiam dui eros, ornare quis tempus vitae, molestie ac dolor. Morbi non suscipit ligula, ac vestibulum purus. In tempor finibus elit, sed molestie erat sagittis eu."},
  {city: "Vancouver",
  country: "Canada",
  link: "gallery/vancouver.jpg",
  info: "Phasellus sed tellus vel lacus luctus dictum. Morbi non sodales libero, dignissim tempus nisi."},
  {city: "Mecixo City",
  country: "Mexico",
  link: "gallery/mexico_city.jpg",
  info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id facilisis augue, sit amet faucibus risus. Nam nisl dui, posuere sit amet porta nec, volutpat a leo. Curabitur sit amet nisi ornare, condimentum nunc rutrum, viverra enim."},
  {city: "Auckland",
  country: "New Zealand",
  link: "gallery/auckland.jpg",
  info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget odio finibus, tempor metus vel, sollicitudin mauris. Proin pharetra, orci sit amet dictum facilisis, orci magna iaculis nunc, a consectetur nisl nisl a lacus."},
  {city: "Beirut",
  country: "Lebanon",
  link: "gallery/beirut.jpg",
  info: "Cras bibendum, felis in placerat pretium, enim nunc blandit felis, in aliquet arcu justo eget purus. Fusce non accumsan elit. Donec sit amet erat laoreet, hendrerit sapien quis, mattis nunc. Suspendisse dictum malesuada eros. Nulla et viverra odio."},
  {city: "Bern",
  country: "Switzerland",
  link: "gallery/bern.jpg",
  info: "Tiam sit amet ornare lorem. Morbi tristique lacus dui, vitae finibus risus malesuada aliquam. Aliquam vitae vulputate diam. Quisque tincidunt dui ipsum, nec suscipit dolor pharetra at. Ut venenatis hendrerit lectus."},
  {city: "Manila",
  country: "Philippines",
  link: "gallery/manila.jpg",
  info: "Nullam sit amet odio porta, ullamcorper est in, laoreet libero. Aenean lobortis nisi aliquam nibh mattis, id consectetur neque suscipit."},
  {city: "New York",
  country: "USA",
  link: "gallery/new_york.jpg",
  info: "Proin metus urna, tristique eget convallis non, fermentum vulputate libero. Quisque id consectetur dui. Nulla scelerisque ante ut venenatis fermentum."},
  {city: "Sao Paulo",
  country: "Brazil",
  link: "gallery/sao_paulo.jpg",
  info: "Maecenas at dolor dui. Donec eget placerat lectus. Phasellus sit amet ullamcorper lorem, at commodo turpis. Aliquam efficitur imperdiet magna sed interdum. Sed bibendum scelerisque aliquet."},
  {city: "Shanghai",
  country: "China",
  link: "gallery/shanghai.jpg",
  info: "Quisque id mauris quam. Duis euismod massa id nisl tincidunt tempus."},
  {city: "Singapore",
  country: "Singapore",
  link: "gallery/singapore.jpg",
  info: "Curabitur vehicula posuere ligula id vestibulum. Fusce consequat maximus dui fermentum scelerisque. Morbi laoreet justo sit amet sem semper fringilla. In fermentum tortor nec tellus commodo, id fermentum justo porttitor. Mauris suscipit elit et tincidunt dictum."},
  {city: "Tokyo",
  country: "Japan",
  link: "gallery/tokyo.jpg",
  info: "Sed gravida rutrum nulla, vitae dapibus elit tristique id. Fusce nec tortor eu sapien commodo efficitur non nec metus. Cras a odio cursus, lobortis neque quis, gravida risus. Sed convallis nisl sagittis urna posuere iaculis. Nulla facilisi. Nullam sagittis dignissim diam a pulvinar."}
];
