var gallery = [
  {city: "Auckland, New Zealand",
  link: "gallery/auckland.jpg",
  info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget odio finibus, tempor metus vel, sollicitudin mauris. Proin pharetra, orci sit amet dictum facilisis, orci magna iaculis nunc, a consectetur nisl nisl a lacus."},
  {city: "Beirut, Libanon",
  link: "gallery/beirut.jpg",
  info: "Cras bibendum, felis in placerat pretium, enim nunc blandit felis, in aliquet arcu justo eget purus. Fusce non accumsan elit. Donec sit amet erat laoreet, hendrerit sapien quis, mattis nunc. Suspendisse dictum malesuada eros. Nulla et viverra odio."},
  {city: "Bern, Switzerland",
  link: "gallery/bern.jpg",
  info: "Tiam sit amet ornare lorem. Morbi tristique lacus dui, vitae finibus risus malesuada aliquam. Aliquam vitae vulputate diam. Quisque tincidunt dui ipsum, nec suscipit dolor pharetra at. Ut venenatis hendrerit lectus."},
  {city: "Manila, Philippines",
  link: "gallery/manila.jpg",
  info: "Nullam sit amet odio porta, ullamcorper est in, laoreet libero. Aenean lobortis nisi aliquam nibh mattis, id consectetur neque suscipit."},
  {city: "New York, USA",
  link: "gallery/new_york.jpg",
  info: "Proin metus urna, tristique eget convallis non, fermentum vulputate libero. Quisque id consectetur dui. Nulla scelerisque ante ut venenatis fermentum."},
  {city: "Sao Paulo, Brazil",
  link: "gallery/sao_paulo.jpg",
  info: "Maecenas at dolor dui. Donec eget placerat lectus. Phasellus sit amet ullamcorper lorem, at commodo turpis. Aliquam efficitur imperdiet magna sed interdum. Sed bibendum scelerisque aliquet."},
  {city: "Shanghai, China",
  link: "gallery/shanghai.jpg",
  info: "Quisque id mauris quam. Duis euismod massa id nisl tincidunt tempus."},
  {city: "Singapore, Singapore",
  link: "gallery/singapore.jpg",
  info: "Curabitur vehicula posuere ligula id vestibulum. Fusce consequat maximus dui fermentum scelerisque. Morbi laoreet justo sit amet sem semper fringilla. In fermentum tortor nec tellus commodo, id fermentum justo porttitor. Mauris suscipit elit et tincidunt dictum."},
  {city: "Tokyo, Japan",
  link: "gallery/tokyo.jpg",
  info: "Sed gravida rutrum nulla, vitae dapibus elit tristique id. Fusce nec tortor eu sapien commodo efficitur non nec metus. Cras a odio cursus, lobortis neque quis, gravida risus. Sed convallis nisl sagittis urna posuere iaculis. Nulla facilisi. Nullam sagittis dignissim diam a pulvinar."}
];
